package com.sba.projecthandler.model;
// Generated Dec 22, 2019 12:04:14 AM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ParentTask generated by hbm2java
 */
@Entity
@Table(name = "parent_task", catalog = "fsd_sba")
public class ParentTask implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6610236909411730890L;
	private Integer parentId;
	private String parentTask;
	private Set<Task> tasks = new HashSet<Task>(0);

	public ParentTask() {
	}
	
	public ParentTask(Integer id) {
		this.parentId = id;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "parent_id", unique = true, nullable = false)
	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	@Column(name = "parent_task", length = 500)
	public String getParentTask() {
		return this.parentTask;
	}

	public void setParentTask(String parentTask) {
		this.parentTask = parentTask;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parentTask")
	public Set<Task> getTasks() {
		return this.tasks;
	}

	public void setTasks(Set<Task> tasks) {
		this.tasks = tasks;
	}

	@Override
	public int hashCode() {
		return Objects.hash(parentId, parentTask, tasks);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ParentTask other = (ParentTask) obj;
		return Objects.equals(parentId, other.parentId) && Objects.equals(parentTask, other.parentTask)
				&& Objects.equals(tasks, other.tasks);
	}
}
